<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xx</groupId>
        <artifactId>xx-cloud</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>xx-cloud-common</artifactId>
    <name>xx-cloud-common</name>
    <packaging>pom</packaging>

    <modules>
        <module>xx-cloud-amqp</module>
        <module>xx-cloud-ip-addr</module>
        <module>xx-cloud-ws</module>
        <module>xx-cloud-redis</module>
        <module>xx-cloud-kafka</module>
        <module>xx-cloud-ws-diy</module>
        <module>xx-cloud-mongo</module>
        <module>xx-cloud-swagger</module>
        <module>xx-cloud-stream</module>
        <module>xx-cloud-event-bus</module>
        <module>xx-cloud-mybatis-plus</module>
        <module>xx-cloud-multi-datasource</module>
        <module>xx-cloud-access-limit</module>
        <module>xx-cloud-netty</module>
        <module>xx-cloud-responsibility-chain</module>
    </modules>

</project>
