<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xx</groupId>
        <artifactId>xx-cloud-business</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>xx-cloud-import-export</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-infra</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
