<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.xx</groupId>
    <artifactId>xx-cloud</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>xx-cloud</name>
    <description>xx-cloud</description>

    <modules>
        <module>xx-cloud-admin</module>
        <module>xx-cloud-infra</module>
        <module>xx-cloud-gateway</module>
        <module>xx-cloud-register</module>
        <module>xxl-job-executor</module>
        <module>xxl-job-admin</module>
        <module>xx-cloud-dependency</module>
        <module>xx-cloud-common</module>
        <module>xx-cloud-base</module>
        <module>xx-cloud-auth</module>
        <module>xx-cloud-business</module>
        <module>xx-cloud-application</module>
        <module>xx-cloud-util</module>
    </modules>

    <properties>
        <maven-compiler-plugin.version>3.8.1</maven-compiler-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <maven-surefire-plugin.version>3.0.0-M5</maven-surefire-plugin.version>
        <!--依赖版本号-->
        <flatten-maven-plugin.version>1.5.0</flatten-maven-plugin.version>
        <revision>1.0.0</revision>
    </properties>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.xx</groupId>
                <artifactId>xx-cloud-dependency</artifactId>
                <version>${revision}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>


    <build>
        <plugins>
            <!-- 统一 revision 版本 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>${flatten-maven-plugin.version}</version>
                <configuration>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                    <updatePomFile>true</updatePomFile>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                    </execution>
                    <execution>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
