<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xx</groupId>
        <artifactId>xx-cloud</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>xx-cloud-base</artifactId>
    <name>xx-cloud-base</name>

    <dependencies>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-infra</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-mongo</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-redis</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-kafka</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-swagger</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-amqp</artifactId>
            <version>${revision}</version>
        </dependency>
        <!--openfeign-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>
        <!--loadbalancer-->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <!--discovery-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <!--jpa -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <!--validation-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-client</artifactId>
        </dependency>
    </dependencies>
</project>
