<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xx</groupId>
        <artifactId>xx-cloud-common</artifactId>
        <version>1.0.0</version>
    </parent>
    <artifactId>xx-cloud-access-limit</artifactId>
    <name>xx-cloud-access-limit</name>


    <dependencies>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-infra</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.xx</groupId>
            <artifactId>xx-cloud-redis</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>
    </dependencies>
</project>
