spring:
  application:
    name: nacos-config
  profiles:
    active: dev

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848 #nacos中心地址
        file-extension: yaml # 配置文件格式


  config:
    import:
      - nacos:${spring.application.name}.yaml