<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xx</groupId>
        <artifactId>xx-cloud-common</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>xx-cloud-ip-addr</artifactId>
    <name>xx-cloud-ip-addr</name>
    <packaging>pom</packaging>

    <modules>
        <module>ip-addr-api</module>
        <module>ip-addr-biz</module>
    </modules>

</project>